# Generated by Django 6.0 on 2026-01-09 18:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostalBoundaries',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('office_name', models.CharField(blank=True, max_length=200, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('circle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Postal Boundary',
                'verbose_name_plural': 'Postal Boundaries',
                'db_table': 'postal_boundaries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PincodeStats',
            fields=[
                ('pincode', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('total_assessments', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('excellent_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('moderate_count', models.IntegerField(default=0)),
                ('concerning_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pincode Statistics',
                'db_table': 'assessment_pincodestats',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=6)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField(default=400)),
                ('user_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('ip_address_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'assessment_assessmentresponse',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['pincode', 'timestamp'], name='assessment__pincode_3312a3_idx'), models.Index(fields=['user_fingerprint', 'timestamp'], name='assessment__user_fi_a5c657_idx')],
            },
        ),
    ]
